---
- name: Install Nginx with SSL certificates on Ubuntu 20.04
  hosts: all
  become: true
  remote_user: root
  ignore_errors: yes

  tasks:
  - name: Install Nginx and OpenSSL
    apt:
      name:
        - nginx
        - openssl
      state: present

  - name: Create SSL directories
    file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
    with_items:
      - /etc/ssl/certs
      - /etc/ssl/private

  - name: Generate a self-signed SSL certificate and key
    command: "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out>
    args:
      creates: /etc/ssl/certs/nginx-selfsigned.crt

  - name: Copy html page
    template:
      src: /var/www/html/index.html
      dest: /var/www/html/index.html

  - name: Configure Nginx with SSL
    template:
      src: /home/ubuntu/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify:
      - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted



